#!/usr/bin/env python3
"""Build a small static HTML site for the UniLab RL task blog docs.

The generator intentionally uses only the Python standard library so the docs
can be previewed without adding a blog framework dependency. It supports the
Markdown subset generated by ``generate_rl_docs.py``: front matter, headings,
paragraphs, lists, blockquotes, fenced code, tables, images, links, and inline
code.
"""

from __future__ import annotations

import html
import io
import json
import keyword
import re
import shutil
import token
import tokenize
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[5]
DOC_ROOT = REPO_ROOT / "docs" / "blog" / "zh_CN" / "rl_tasks"
SITE_ROOT = DOC_ROOT / "_site"


@dataclass(frozen=True)
class Page:
    source: Path
    output: Path
    rel_source: Path
    rel_output: Path
    title: str
    category: str


def _strip_front_matter(text: str) -> tuple[dict[str, str], str]:
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---\n", 4)
    if end < 0:
        return {}, text
    raw = text[4:end].strip()
    body = text[end + 5 :]
    front_matter: dict[str, str] = {}
    for line in raw.splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        front_matter[key.strip()] = value.strip().strip('"')
    return front_matter, body


def _title_from_markdown(front_matter: dict[str, str], body: str, fallback: str) -> str:
    if "title" in front_matter:
        return front_matter["title"]
    for line in body.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return fallback


def _site_output_for(md_path: Path) -> Path:
    rel = md_path.relative_to(DOC_ROOT)
    if rel.name == "README.md":
        if rel.parent == Path("."):
            return SITE_ROOT / "index.html"
        return SITE_ROOT / rel.parent / "index.html"
    return SITE_ROOT / rel.with_suffix(".html")


def _page_category(rel_source: Path) -> str:
    parts = rel_source.parts
    if parts[0] == "robots":
        return "机器人"
    if parts[0] == "tasks" and len(parts) > 1:
        return {
            "locomotion": "运动控制",
            "motion_tracking": "动作追踪",
            "manipulation": "灵巧操作",
            "manip_loco": "移动操作",
        }.get(parts[1], parts[1])
    if parts[0] == "_generated":
        return "生成清单"
    return "总览"


def collect_pages() -> list[Page]:
    pages: list[Page] = []
    for md_path in sorted(DOC_ROOT.rglob("*.md")):
        if "_site" in md_path.parts:
            continue
        front_matter, body = _strip_front_matter(md_path.read_text(encoding="utf-8"))
        output = _site_output_for(md_path)
        rel_source = md_path.relative_to(DOC_ROOT)
        rel_output = output.relative_to(SITE_ROOT)
        pages.append(
            Page(
                source=md_path,
                output=output,
                rel_source=rel_source,
                rel_output=rel_output,
                title=_title_from_markdown(front_matter, body, rel_source.stem),
                category=_page_category(rel_source),
            )
        )
    return pages


def _html_page_for_md(md_rel: str) -> str:
    path = Path(md_rel)
    if path.name == "README.md":
        if path.parent == Path("."):
            return "index.html"
        return str(path.parent / "index.html")
    return str(path.with_suffix(".html"))


def _convert_link(url: str) -> str:
    if "://" in url or url.startswith("#") or url.startswith("mailto:"):
        return url
    if url.endswith(".md"):
        return _html_page_for_md(url)
    return url


def _inline(markdown: str) -> str:
    escaped = html.escape(markdown)

    def image_repl(match: re.Match[str]) -> str:
        alt = html.escape(match.group(1))
        src = html.escape(_convert_link(match.group(2)))
        return f'<img src="{src}" alt="{alt}" loading="lazy">'

    def link_repl(match: re.Match[str]) -> str:
        label = match.group(1)
        href = html.escape(_convert_link(match.group(2)))
        return f'<a href="{href}">{label}</a>'

    escaped = re.sub(r"!\[([^\]]*)\]\(([^)]+)\)", image_repl, escaped)
    escaped = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", link_repl, escaped)
    escaped = re.sub(r"`([^`]+)`", r"<code>\1</code>", escaped)
    return escaped


def _slug(text: str) -> str:
    cleaned = re.sub(r"[^\w\u4e00-\u9fff-]+", "-", text.strip().lower())
    return cleaned.strip("-") or "section"


def _is_table_separator(line: str) -> bool:
    stripped = line.strip()
    marker = stripped.replace("|", "").replace(" ", "").strip()
    return bool(stripped.startswith("|") and marker and set(marker) <= {"-", ":"})


def _split_table_row(line: str) -> list[str]:
    stripped = line.strip().strip("|")
    cells: list[str] = []
    current: list[str] = []
    index = 0
    while index < len(stripped):
        char = stripped[index]
        if char == "\\" and index + 1 < len(stripped) and stripped[index + 1] == "|":
            current.append("|")
            index += 2
            continue
        if char == "|":
            cells.append("".join(current).strip())
            current = []
        else:
            current.append(char)
        index += 1
    cells.append("".join(current).strip())
    return cells


def _render_table(lines: list[str]) -> str:
    headers = _split_table_row(lines[0])
    body_rows = [_split_table_row(line) for line in lines[2:]]
    out = ["<div class=\"table-wrap\"><table><thead><tr>"]
    out.extend(f"<th>{_inline(cell)}</th>" for cell in headers)
    out.append("</tr></thead><tbody>")
    for row in body_rows:
        out.append("<tr>")
        out.extend(f"<td>{_inline(cell)}</td>" for cell in row)
        out.append("</tr>")
    out.append("</tbody></table></div>")
    return "".join(out)


PY_BUILTINS = {
    "Any",
    "None",
    "True",
    "False",
    "dict",
    "list",
    "tuple",
    "set",
    "str",
    "int",
    "float",
    "bool",
    "len",
    "range",
    "super",
    "self",
    "cls",
}


def _tok(cls: str, value: str) -> str:
    return f'<span class="tok-{cls}">{html.escape(value)}</span>'


def _highlight_python(code: str) -> str:
    lines = code.splitlines(keepends=True)
    if not lines:
        return ""

    rendered: list[str] = []
    last_line = 1
    last_col = 0

    def append_gap(start_line: int, start_col: int) -> None:
        nonlocal last_line, last_col
        while last_line < start_line and last_line <= len(lines):
            rendered.append(html.escape(lines[last_line - 1][last_col:]))
            last_line += 1
            last_col = 0
        if last_line <= len(lines):
            rendered.append(html.escape(lines[last_line - 1][last_col:start_col]))
            last_col = start_col

    try:
        tokens = tokenize.generate_tokens(io.StringIO(code).readline)
        for tok in tokens:
            tok_type = tok.type
            tok_text = tok.string
            start_line, start_col = tok.start
            end_line, end_col = tok.end
            if tok_type in {token.ENDMARKER, token.ENCODING}:
                continue
            append_gap(start_line, start_col)
            if tok_type == token.NAME and keyword.iskeyword(tok_text):
                rendered.append(_tok("kw", tok_text))
            elif tok_type == token.NAME and tok_text in PY_BUILTINS:
                rendered.append(_tok("builtin", tok_text))
            elif tok_type == token.STRING:
                rendered.append(_tok("str", tok_text))
            elif tok_type == token.NUMBER:
                rendered.append(_tok("num", tok_text))
            elif tok_type == tokenize.COMMENT:
                rendered.append(_tok("comment", tok_text))
            elif tok_type == token.OP:
                rendered.append(_tok("op", tok_text))
            else:
                rendered.append(html.escape(tok_text))
            last_line = end_line
            last_col = end_col
        append_gap(len(lines), len(lines[-1]))
    except (IndentationError, tokenize.TokenError):
        return _highlight_plain(code)
    return "".join(rendered)


def _highlight_plain(code: str) -> str:
    return html.escape(code)


def _highlight_mapping_lang(code: str) -> str:
    escaped = html.escape(code)
    escaped = re.sub(r'(".*?")', r'<span class="tok-str">\1</span>', escaped)
    escaped = re.sub(
        r"(^|\n)(\s*)([A-Za-z_][\w.-]*)(:)",
        r'\1\2<span class="tok-key">\3</span>\4',
        escaped,
    )
    escaped = re.sub(r"(?<![\w.-])(-?\d+(?:\.\d+)?)(?![\w.-])", r'<span class="tok-num">\1</span>', escaped)
    escaped = re.sub(r"(^|\s)(#.*)$", r'\1<span class="tok-comment">\2</span>', escaped, flags=re.M)
    return escaped


def _highlight_xml(code: str) -> str:
    def highlight_tag(tag: str) -> str:
        if tag.startswith("&lt;!--"):
            return f'<span class="tok-comment">{tag}</span>'
        match = re.match(r"(&lt;/?)([\w:.-]+)(.*?)(/?&gt;)$", tag, flags=re.S)
        if match is None:
            return tag
        prefix, name, attrs, suffix = match.groups()
        highlighted_attrs = re.sub(
            r"([\w:.-]+)(=)(&quot;.*?&quot;)",
            r'<span class="tok-attr">\1</span>\2<span class="tok-str">\3</span>',
            attrs,
        )
        return f'{prefix}<span class="tok-tag">{name}</span>{highlighted_attrs}{suffix}'

    escaped = html.escape(code)
    return re.sub(r"&lt;!--.*?--&gt;|&lt;/?[\w:.-]+.*?/?&gt;", lambda match: highlight_tag(match.group(0)), escaped)


def _leading_spaces(line: str) -> int:
    return len(line) - len(line.lstrip(" "))


def _normalize_python_comment_indents(code: str) -> str:
    """Indent hand-written comment-only lines to match nearby Python code."""
    lines = code.splitlines()
    normalized = list(lines)
    path_comment = re.compile(r"^#\s*(src|conf|docs|未在|pyright|ruff|noqa)\b")

    def previous_code_indent(index: int) -> tuple[int, str] | None:
        for prev in range(index - 1, -1, -1):
            stripped = lines[prev].strip()
            if stripped and not stripped.startswith("#"):
                return _leading_spaces(lines[prev]), stripped
        return None

    def next_code_indent(index: int) -> tuple[int, str] | None:
        for nxt in range(index + 1, len(lines)):
            stripped = lines[nxt].strip()
            if stripped and not stripped.startswith("#"):
                return _leading_spaces(lines[nxt]), stripped
        return None

    for index, line in enumerate(lines):
        if not line.startswith("#") or path_comment.match(line):
            continue

        prev = previous_code_indent(index)
        nxt = next_code_indent(index)
        if prev is None and nxt is None:
            continue
        if prev is None:
            target_indent = nxt[0] if nxt is not None else 0
        elif nxt is None:
            target_indent = prev[0]
        else:
            prev_indent, prev_text = prev
            next_indent, _ = nxt
            if prev_text.endswith((":", "(", "[", "{")) and next_indent > prev_indent:
                target_indent = next_indent
            elif next_indent == 0 and prev_indent == 0:
                target_indent = 0
            elif prev_indent == 0:
                target_indent = next_indent
            elif next_indent == 0:
                target_indent = prev_indent
            else:
                target_indent = min(prev_indent, next_indent)

        if target_indent > 0:
            normalized[index] = " " * target_indent + line

    return "\n".join(normalized)


def _highlight_code(code: str, lang: str) -> str:
    normalized = lang.strip().lower().split(maxsplit=1)[0] if lang.strip() else "text"
    if normalized in {"py", "python"}:
        code = _normalize_python_comment_indents(code)
        return _highlight_python(code)
    if normalized in {"yaml", "yml", "json", "toml"}:
        return _highlight_mapping_lang(code)
    if normalized in {"xml", "html"}:
        return _highlight_xml(code)
    return _highlight_plain(code)


def _render_code_block(code_lines: list[str], lang: str) -> str:
    code = "\n".join(code_lines)
    safe_lang = re.sub(r"[^a-zA-Z0-9_-]+", "-", lang.strip().lower()) or "text"
    highlighted = _highlight_code(code, lang)
    return f'<pre class="code-block language-{safe_lang}"><code>{highlighted}</code></pre>'


def markdown_to_html(markdown: str) -> str:
    _, markdown = _strip_front_matter(markdown)
    lines = markdown.splitlines()
    out: list[str] = []
    paragraph: list[str] = []
    list_open = False
    quote_open = False
    code_open = False
    code_lang = ""
    code_lines: list[str] = []
    index = 0

    def flush_paragraph() -> None:
        nonlocal paragraph
        if paragraph:
            out.append(f"<p>{_inline(' '.join(paragraph))}</p>")
            paragraph = []

    def close_list() -> None:
        nonlocal list_open
        if list_open:
            out.append("</ul>")
            list_open = False

    def close_quote() -> None:
        nonlocal quote_open
        if quote_open:
            out.append("</blockquote>")
            quote_open = False

    while index < len(lines):
        line = lines[index]
        stripped = line.strip()

        if code_open:
            if stripped.startswith("```"):
                out.append(_render_code_block(code_lines, code_lang))
                code_open = False
                code_lang = ""
                code_lines = []
            else:
                code_lines.append(line)
            index += 1
            continue

        if stripped.startswith("```"):
            flush_paragraph()
            close_list()
            close_quote()
            code_open = True
            code_lang = stripped[3:].strip()
            index += 1
            continue

        if stripped in {"<details>", "</details>"} or stripped.startswith("<summary>"):
            flush_paragraph()
            close_list()
            close_quote()
            out.append(stripped)
            index += 1
            continue

        if not stripped:
            flush_paragraph()
            close_list()
            close_quote()
            index += 1
            continue

        if stripped.startswith("|") and index + 1 < len(lines) and _is_table_separator(lines[index + 1]):
            flush_paragraph()
            close_list()
            close_quote()
            table_lines = [line, lines[index + 1]]
            index += 2
            while index < len(lines) and lines[index].strip().startswith("|"):
                table_lines.append(lines[index])
                index += 1
            out.append(_render_table(table_lines))
            continue

        heading = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if heading:
            flush_paragraph()
            close_list()
            close_quote()
            level = len(heading.group(1))
            text = heading.group(2).strip()
            out.append(f'<h{level} id="{_slug(text)}">{_inline(text)}</h{level}>')
            index += 1
            continue

        if stripped.startswith(">"):
            flush_paragraph()
            close_list()
            if not quote_open:
                out.append("<blockquote>")
                quote_open = True
            out.append(f"<p>{_inline(stripped.lstrip('>').strip())}</p>")
            index += 1
            continue

        if stripped.startswith("- "):
            flush_paragraph()
            close_quote()
            if not list_open:
                out.append("<ul>")
                list_open = True
            out.append(f"<li>{_inline(stripped[2:].strip())}</li>")
            index += 1
            continue

        close_list()
        close_quote()
        paragraph.append(stripped)
        index += 1

    flush_paragraph()
    close_list()
    close_quote()
    return "\n".join(out)


def _nav_html(pages: list[Page], current: Page) -> str:
    groups: dict[str, list[Page]] = {}
    for page in pages:
        if page.rel_source.parts[0] == "_generated":
            continue
        groups.setdefault(page.category, []).append(page)

    current_dir = current.output.parent
    blocks = []
    for category, group_pages in groups.items():
        blocks.append(f"<section><h3>{html.escape(category)}</h3><ul>")
        for page in group_pages:
            href = html.escape(str(Path(*([".."] * len(current.output.parent.relative_to(SITE_ROOT).parts))) / page.rel_output))
            if current_dir == page.output.parent:
                href = html.escape(page.output.name)
            if current.output == page.output:
                blocks.append(f'<li class="active">{html.escape(page.title)}</li>')
            else:
                blocks.append(f'<li><a href="{href}">{html.escape(page.title)}</a></li>')
        blocks.append("</ul></section>")
    return "\n".join(blocks)


def _relative_asset(current: Page, target: str) -> str:
    depth = len(current.output.parent.relative_to(SITE_ROOT).parts)
    return str(Path(*([".."] * depth)) / target) if depth else target


def _relative_prefix(current: Page) -> str:
    depth = len(current.output.parent.relative_to(SITE_ROOT).parts)
    if depth == 0:
        return ""
    return "../" * depth


def _page_kind(page: Page) -> str:
    if page.rel_source == Path("README.md"):
        return "home"
    if page.rel_source.parts[0] == "robots":
        return "robot"
    if page.rel_source.parts[0] == "tasks":
        return "task"
    return "reference"


def _hero_subtitle(page: Page) -> str:
    kind = _page_kind(page)
    if kind == "home":
        return "把 UniLab 的机器人资产、强化学习任务、观测、动作、奖励和源码证据整理成一套可浏览的知识地图。"
    if kind == "robot":
        return "机器人资产、MJCF 场景、关节中文含义、执行器顺序和传感器信息的结构化说明。"
    if kind == "task":
        return "从 agent、env、obs、action、reward、初始状态、终止条件和域随机化八个角度拆解任务实现。"
    return "由文档生成器输出的事实清单和验证结果。"


def _stats_html(page: Page, pages: list[Page]) -> str:
    if _page_kind(page) != "home":
        return ""
    robot_count = sum(1 for item in pages if item.category == "机器人")
    task_count = sum(1 for item in pages if item.rel_source.parts[0] == "tasks" and item.rel_source.name != "README.md")
    category_count = len({item.category for item in pages if item.rel_source.parts[0] == "tasks"})
    return f"""
    <div class="hero-stats" aria-label="文档统计">
      <div><strong>{task_count}</strong><span>RL 任务</span></div>
      <div><strong>{robot_count}</strong><span>机器人</span></div>
      <div><strong>{category_count}</strong><span>任务分类</span></div>
      <div><strong>32</strong><span>渲染图</span></div>
    </div>
"""


def _hero_html(page: Page, pages: list[Page]) -> str:
    kind = _page_kind(page)
    return f"""
    <header class="hero hero-{kind}">
      <div class="hero-copy">
        <div class="eyebrow">{html.escape(page.category)} · UniLab RL Tasks</div>
        <h1>{html.escape(page.title)}</h1>
        <p>{html.escape(_hero_subtitle(page))}</p>
        {_stats_html(page, pages)}
      </div>
      <div class="hero-orbit" aria-hidden="true">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </header>
"""


def _floating_toc_html(body: str) -> str:
    headings: list[tuple[int, str, str]] = []
    pattern = re.compile(r'<h([23]) id="([^"]+)">(.*?)</h\1>')
    for match in pattern.finditer(body):
        level = int(match.group(1))
        anchor = match.group(2)
        raw_title = re.sub(r"<[^>]+>", "", match.group(3))
        title = html.unescape(raw_title).strip()
        if not title:
            continue
        headings.append((level, anchor, title))

    if not headings:
        fallback_pattern = re.compile(r'<h1 id="([^"]+)">(.*?)</h1>')
        for match in fallback_pattern.finditer(body):
            anchor = match.group(1)
            raw_title = re.sub(r"<[^>]+>", "", match.group(2))
            title = html.unescape(raw_title).strip()
            if title:
                headings.append((1, anchor, title))

    if not headings:
        return ""

    items = []
    for level, anchor, title in headings:
        items.append(
            f'<a class="toc-level-{level}" href="#{html.escape(anchor)}">'
            f"{html.escape(title)}</a>"
        )
    return f"""
    <aside class="page-toc" aria-label="本页目录">
      <div class="page-toc-title">本页目录</div>
      <nav>
        {"".join(items)}
      </nav>
    </aside>
"""


def _layout(page: Page, pages: list[Page], body: str) -> str:
    style_href = _relative_asset(page, "site.css")
    search_href = _relative_asset(page, "search-index.json")
    search_prefix = _relative_prefix(page)
    root_href = _relative_asset(page, "index.html")
    body_class = f"page-{_page_kind(page)}"
    toc_html = _floating_toc_html(body)
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(page.title)} · UniLab RL Tasks</title>
  <link rel="stylesheet" href="{style_href}">
</head>
<body class="{body_class}">
  <div class="ambient ambient-a"></div>
  <div class="ambient ambient-b"></div>
  <aside class="sidebar">
    <a class="brand" href="{root_href}">
      <span class="brand-mark">RL</span>
      <span><strong>UniLab</strong><small>Task Atlas</small></span>
    </a>
    <div class="sidebar-card">
      <span>Contract driven</span>
      <strong>Robot Learning Docs</strong>
      <p>任务、资产、源码和配置的一站式索引。</p>
    </div>
    <label class="search-label" for="search">快速搜索</label>
    <input id="search" type="search" placeholder="例如 G1、reward、action..." autocomplete="off">
    <div id="search-results" class="search-results"></div>
    <nav>{_nav_html(pages, page)}</nav>
  </aside>
  <main class="main-stage">
    {_hero_html(page, pages)}
    {toc_html}
    <article class="doc-article">
      {body}
    </article>
  </main>
  <script>window.SEARCH_INDEX_URL = "{search_href}";</script>
  <script>window.SITE_ROOT_PREFIX = "{search_prefix}";</script>
  <script src="{_relative_asset(page, "site.js")}"></script>
</body>
</html>
"""


def write_assets() -> None:
    css = """
:root {
  color-scheme: dark;
  --bg: #070b17;
  --bg-soft: #0d1324;
  --panel: rgba(15, 23, 42, .78);
  --panel-solid: #101827;
  --text: #edf5ff;
  --muted: #95a6c5;
  --border: rgba(148, 163, 184, .2);
  --border-strong: rgba(148, 163, 184, .32);
  --accent: #67e8f9;
  --accent-2: #a78bfa;
  --accent-3: #34d399;
  --code: rgba(8, 13, 26, .86);
  --shadow: 0 24px 80px rgba(0, 0, 0, .38);
}
@media (prefers-color-scheme: light) {
  :root {
    color-scheme: light;
    --bg: #eef4ff;
    --bg-soft: #f8fbff;
    --panel: rgba(255, 255, 255, .82);
    --panel-solid: #ffffff;
    --text: #111827;
    --muted: #5b6b85;
    --border: rgba(15, 23, 42, .12);
    --border-strong: rgba(15, 23, 42, .18);
    --code: rgba(241, 245, 249, .92);
    --shadow: 0 24px 70px rgba(30, 64, 175, .14);
  }
}
* { box-sizing: border-box; }
body {
  margin: 0;
  min-height: 100vh;
  font-family:
    Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI",
    "Noto Sans CJK SC", "Microsoft YaHei", sans-serif;
  background:
    radial-gradient(circle at 18% -8%, rgba(103, 232, 249, .2), transparent 30rem),
    radial-gradient(circle at 85% 12%, rgba(167, 139, 250, .22), transparent 34rem),
    linear-gradient(135deg, var(--bg), var(--bg-soft) 58%, var(--bg));
  color: var(--text);
  overflow-x: hidden;
}
body::before {
  content: "";
  position: fixed;
  inset: 0;
  pointer-events: none;
  background-image:
    linear-gradient(rgba(148, 163, 184, .06) 1px, transparent 1px),
    linear-gradient(90deg, rgba(148, 163, 184, .06) 1px, transparent 1px);
  background-size: 48px 48px;
  mask-image: linear-gradient(to bottom, rgba(0, 0, 0, .72), transparent 72%);
}
.ambient {
  position: fixed;
  pointer-events: none;
  z-index: 0;
  filter: blur(10px);
  opacity: .72;
}
.ambient-a {
  width: 34rem;
  height: 34rem;
  right: -11rem;
  top: 10rem;
  background: radial-gradient(circle, rgba(103, 232, 249, .18), transparent 65%);
}
.ambient-b {
  width: 28rem;
  height: 28rem;
  left: 18rem;
  bottom: -10rem;
  background: radial-gradient(circle, rgba(52, 211, 153, .13), transparent 64%);
}
a { color: var(--accent); text-decoration: none; }
a:hover { color: #cffafe; text-decoration: none; }
.sidebar {
  position: fixed;
  inset: 0 auto 0 0;
  z-index: 4;
  width: 336px;
  overflow: auto;
  padding: 24px 18px 30px;
  background:
    linear-gradient(180deg, rgba(15, 23, 42, .9), rgba(15, 23, 42, .66)),
    var(--panel);
  backdrop-filter: blur(22px);
  border-right: 1px solid var(--border);
  box-shadow: 20px 0 70px rgba(0, 0, 0, .24);
}
.brand {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 18px;
  color: var(--text);
}
.brand:hover { color: var(--text); }
.brand-mark {
  display: grid;
  place-items: center;
  width: 46px;
  height: 46px;
  border-radius: 16px;
  color: #06111f;
  font-weight: 900;
  letter-spacing: -.04em;
  background: linear-gradient(135deg, var(--accent), var(--accent-3));
  box-shadow: 0 12px 38px rgba(103, 232, 249, .28);
}
.brand strong {
  display: block;
  font-size: 20px;
  letter-spacing: -.03em;
}
.brand small {
  display: block;
  margin-top: 2px;
  color: var(--muted);
  font-size: 12px;
  letter-spacing: .12em;
  text-transform: uppercase;
}
.sidebar-card {
  margin: 0 0 18px;
  padding: 16px;
  border: 1px solid var(--border);
  border-radius: 20px;
  background:
    linear-gradient(135deg, rgba(103, 232, 249, .13), rgba(167, 139, 250, .09)),
    rgba(15, 23, 42, .45);
}
.sidebar-card span {
  color: var(--accent);
  font-size: 12px;
  font-weight: 800;
  letter-spacing: .11em;
  text-transform: uppercase;
}
.sidebar-card strong {
  display: block;
  margin-top: 8px;
  font-size: 16px;
}
.sidebar-card p {
  margin: 6px 0 0;
  color: var(--muted);
  font-size: 13px;
  line-height: 1.55;
}
.search-label {
  display: block;
  margin: 16px 4px 8px;
  color: var(--muted);
  font-size: 12px;
  font-weight: 700;
  letter-spacing: .08em;
  text-transform: uppercase;
}
#search {
  width: 100%;
  padding: 13px 14px;
  border: 1px solid var(--border);
  border-radius: 16px;
  outline: none;
  background: rgba(2, 6, 23, .42);
  color: var(--text);
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, .04);
}
#search:focus {
  border-color: rgba(103, 232, 249, .58);
  box-shadow: 0 0 0 4px rgba(103, 232, 249, .12);
}
.search-results {
  margin: 12px 0 18px;
  font-size: 14px;
}
.search-results ul { list-style: none; margin: 0; padding: 0; }
.search-results li { margin: 8px 0; }
.search-results a {
  display: block;
  padding: 10px 12px;
  border: 1px solid var(--border);
  border-radius: 14px;
  color: var(--text);
  background: rgba(15, 23, 42, .5);
}
.search-results small {
  display: block;
  margin-top: 3px;
  color: var(--muted);
}
nav { padding-top: 4px; }
nav section {
  margin-bottom: 18px;
  padding-bottom: 14px;
  border-bottom: 1px solid rgba(148, 163, 184, .1);
}
nav section:last-child { border-bottom: 0; }
nav h3 {
  margin: 12px 4px 8px;
  color: var(--muted);
  font-size: 12px;
  font-weight: 800;
  letter-spacing: .12em;
  text-transform: uppercase;
}
nav ul { list-style: none; margin: 0; padding: 0; }
nav li { margin: 3px 0; line-height: 1.35; }
nav li.active {
  position: relative;
  padding: 9px 11px 9px 15px;
  border: 1px solid rgba(103, 232, 249, .28);
  border-radius: 13px;
  color: #e0fbff;
  background: linear-gradient(90deg, rgba(103, 232, 249, .18), rgba(167, 139, 250, .08));
}
nav li.active::before {
  content: "";
  position: absolute;
  left: 6px;
  top: 50%;
  width: 4px;
  height: 18px;
  border-radius: 999px;
  background: var(--accent);
  transform: translateY(-50%);
}
nav a {
  display: block;
  padding: 9px 11px;
  border-radius: 13px;
  color: rgba(237, 245, 255, .84);
  transition: .16s ease;
}
nav a:hover {
  color: var(--text);
  background: rgba(148, 163, 184, .11);
  transform: translateX(3px);
}
.main-stage {
  position: relative;
  z-index: 1;
  max-width: 1280px;
  margin-left: 336px;
  padding: 34px 52px 90px;
}
.page-toc {
  position: fixed;
  top: 118px;
  right: 22px;
  z-index: 20;
  width: 238px;
  max-height: min(68vh, 720px);
  padding: 16px;
  border: 1px solid rgba(148, 163, 184, .18);
  border-radius: 22px;
  background:
    linear-gradient(145deg, rgba(15, 23, 42, .86), rgba(2, 6, 23, .72)),
    rgba(15, 23, 42, .82);
  box-shadow: 0 22px 60px rgba(0, 0, 0, .28);
  backdrop-filter: blur(18px);
}
.page-toc-title {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 12px;
  color: #e7fbff;
  font-size: 13px;
  font-weight: 900;
  letter-spacing: .08em;
  text-transform: uppercase;
}
.page-toc-title::before {
  content: "";
  width: 8px;
  height: 8px;
  border-radius: 999px;
  background: linear-gradient(135deg, var(--accent), var(--accent-2));
  box-shadow: 0 0 18px rgba(103, 232, 249, .75);
}
.page-toc nav {
  display: grid;
  gap: 4px;
  max-height: calc(min(68vh, 720px) - 52px);
  overflow: auto;
  padding-right: 4px;
}
.page-toc a {
  display: block;
  padding: 7px 9px;
  border-radius: 12px;
  color: rgba(226, 238, 255, .68);
  font-size: 13px;
  line-height: 1.35;
  text-decoration: none;
  transition: color .16s ease, background .16s ease, transform .16s ease;
}
.page-toc a:hover,
.page-toc a.active {
  color: #06111f;
  background: linear-gradient(135deg, var(--accent), var(--accent-3));
  transform: translateX(-2px);
}
.page-toc .toc-level-1 {
  color: rgba(226, 238, 255, .82);
  font-weight: 800;
}
.page-toc .toc-level-3 {
  margin-left: 12px;
  color: rgba(203, 213, 225, .6);
  font-size: 12px;
}
.hero {
  position: relative;
  display: grid;
  grid-template-columns: minmax(0, 1fr) 260px;
  gap: 28px;
  min-height: 260px;
  margin: 0 0 28px;
  padding: 42px;
  overflow: hidden;
  border: 1px solid var(--border);
  border-radius: 34px;
  background:
    linear-gradient(135deg, rgba(103, 232, 249, .18), rgba(167, 139, 250, .12) 44%, rgba(52, 211, 153, .08)),
    rgba(15, 23, 42, .62);
  box-shadow: var(--shadow);
  backdrop-filter: blur(18px);
}
.hero::before {
  content: "";
  position: absolute;
  inset: 1px;
  pointer-events: none;
  border-radius: 33px;
  background:
    radial-gradient(circle at 22% 16%, rgba(255, 255, 255, .16), transparent 22rem),
    linear-gradient(180deg, rgba(255, 255, 255, .08), transparent 34%);
}
.hero-copy {
  position: relative;
  z-index: 1;
  align-self: end;
}
.eyebrow {
  display: inline-flex;
  margin-bottom: 16px;
  padding: 8px 12px;
  border: 1px solid rgba(103, 232, 249, .28);
  border-radius: 999px;
  color: #c8fbff;
  background: rgba(8, 13, 26, .36);
  font-size: 12px;
  font-weight: 800;
  letter-spacing: .12em;
  text-transform: uppercase;
}
.hero h1 {
  max-width: 850px;
  margin: 0;
  font-size: clamp(42px, 6vw, 82px);
  line-height: .95;
  letter-spacing: -.07em;
}
.page-task .hero h1,
.page-robot .hero h1,
.page-reference .hero h1 {
  font-size: clamp(34px, 4vw, 58px);
  line-height: 1.02;
}
.hero p {
  max-width: 760px;
  margin: 20px 0 0;
  color: var(--muted);
  font-size: 18px;
  line-height: 1.75;
}
.hero-stats {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 12px;
  max-width: 760px;
  margin-top: 28px;
}
.hero-stats div {
  padding: 16px;
  border: 1px solid var(--border);
  border-radius: 18px;
  background: rgba(2, 6, 23, .28);
}
.hero-stats strong {
  display: block;
  color: var(--accent);
  font-size: 30px;
  line-height: 1;
}
.hero-stats span {
  display: block;
  margin-top: 7px;
  color: var(--muted);
  font-size: 13px;
}
.hero-orbit {
  position: relative;
  z-index: 1;
  display: grid;
  place-items: center;
}
.hero-orbit span {
  position: absolute;
  border: 1px solid rgba(103, 232, 249, .24);
  border-radius: 999px;
  transform: rotate(-18deg);
}
.hero-orbit span:nth-child(1) { width: 230px; height: 230px; }
.hero-orbit span:nth-child(2) { width: 165px; height: 165px; border-color: rgba(167, 139, 250, .3); transform: rotate(28deg); }
.hero-orbit span:nth-child(3) {
  width: 76px;
  height: 76px;
  border: 0;
  background: radial-gradient(circle, var(--accent), rgba(103, 232, 249, .08) 68%);
  box-shadow: 0 0 70px rgba(103, 232, 249, .5);
}
.doc-article {
  padding: 36px 42px 56px;
  border: 1px solid var(--border);
  border-radius: 30px;
  background: rgba(15, 23, 42, .72);
  box-shadow: var(--shadow);
  backdrop-filter: blur(18px);
}
.doc-article > h1:first-child { display: none; }
.doc-article > p:first-of-type {
  margin-top: 0;
  color: #dce9ff;
  font-size: 18px;
}
.doc-article h2 {
  position: relative;
  margin: 48px 0 18px;
  padding-top: 26px;
  border-top: 1px solid var(--border);
  font-size: 28px;
  letter-spacing: -.03em;
}
.doc-article h2::before {
  content: "";
  position: absolute;
  top: -2px;
  left: 0;
  width: 84px;
  height: 3px;
  border-radius: 999px;
  background: linear-gradient(90deg, var(--accent), var(--accent-2));
}
.doc-article h3 {
  margin: 32px 0 12px;
  color: #dffcff;
  font-size: 20px;
}
.doc-article p,
.doc-article li {
  color: rgba(237, 245, 255, .86);
  line-height: 1.85;
}
.doc-article ul {
  padding: 18px 20px 18px 30px;
  border: 1px solid var(--border);
  border-radius: 18px;
  background: rgba(2, 6, 23, .24);
}
.doc-article li + li { margin-top: 7px; }
.doc-article img {
  display: block;
  max-width: min(100%, 980px);
  margin: 26px auto;
  border: 1px solid var(--border-strong);
  border-radius: 24px;
  background: var(--panel-solid);
  box-shadow: 0 20px 60px rgba(0, 0, 0, .32);
  transition: transform .2s ease, box-shadow .2s ease;
}
.doc-article img:hover {
  transform: translateY(-3px);
  box-shadow: 0 28px 80px rgba(0, 0, 0, .38);
}
.doc-article code {
  padding: 3px 7px;
  border: 1px solid rgba(148, 163, 184, .15);
  border-radius: 7px;
  color: #d8fbff;
  background: rgba(2, 6, 23, .55);
}
.doc-article pre {
  overflow: auto;
  margin: 20px 0;
  padding: 20px 22px;
  border: 1px solid var(--border);
  border-radius: 20px;
  background:
    radial-gradient(circle at 12% 0%, rgba(103, 232, 249, .10), transparent 30%),
    linear-gradient(180deg, rgba(255, 255, 255, .035), transparent),
    var(--code);
  box-shadow:
    inset 0 1px 0 rgba(255, 255, 255, .05),
    0 16px 46px rgba(0, 0, 0, .22);
}
.doc-article pre code {
  padding: 0;
  border: 0;
  color: #d8e8ff;
  background: transparent;
  font-size: 13px;
  line-height: 1.72;
  tab-size: 4;
}
.tok-kw { color: #c084fc; font-weight: 800; }
.tok-builtin { color: #67e8f9; }
.tok-str { color: #86efac; }
.tok-num { color: #fbbf24; }
.tok-comment { color: #94a3b8; font-style: italic; }
.tok-op { color: #f8fafc; }
.tok-key { color: #93c5fd; font-weight: 700; }
.tok-tag { color: #67e8f9; font-weight: 800; }
.tok-attr { color: #f9a8d4; }
.doc-article pre .tok-comment:has(+ *) {
  opacity: .95;
}
.doc-article blockquote {
  margin: 24px 0;
  padding: 18px 20px;
  border: 1px solid rgba(103, 232, 249, .22);
  border-left: 5px solid var(--accent);
  border-radius: 18px;
  color: #dffcff;
  background: linear-gradient(90deg, rgba(103, 232, 249, .14), rgba(167, 139, 250, .06));
}
.doc-article details {
  margin: 22px 0;
  border: 1px solid var(--border);
  border-radius: 22px;
  background:
    linear-gradient(135deg, rgba(103, 232, 249, .08), rgba(167, 139, 250, .05)),
    rgba(2, 6, 23, .24);
  overflow: hidden;
}
.doc-article summary {
  cursor: pointer;
  padding: 16px 18px;
  color: #dffcff;
  font-weight: 800;
  letter-spacing: .01em;
  list-style: none;
}
.doc-article summary::-webkit-details-marker { display: none; }
.doc-article summary::before {
  content: "展开";
  display: inline-flex;
  margin-right: 10px;
  padding: 3px 8px;
  border-radius: 999px;
  color: #06111f;
  background: linear-gradient(135deg, var(--accent), var(--accent-3));
  font-size: 12px;
}
.doc-article details[open] summary::before { content: "收起"; }
.doc-article details .table-wrap {
  margin: 0 16px 16px;
}
.table-wrap {
  overflow: auto;
  margin: 22px 0;
  border: 1px solid var(--border);
  border-radius: 22px;
  background: rgba(2, 6, 23, .32);
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, .04);
}
table {
  width: 100%;
  border-collapse: separate;
  border-spacing: 0;
  font-size: 14px;
}
th,
td {
  padding: 13px 15px;
  border-bottom: 1px solid rgba(148, 163, 184, .13);
  vertical-align: top;
}
th {
  position: sticky;
  top: 0;
  z-index: 1;
  text-align: left;
  color: #e7fbff;
  background: rgba(15, 23, 42, .94);
}
tbody tr:nth-child(2n) td { background: rgba(148, 163, 184, .035); }
tbody tr:hover td { background: rgba(103, 232, 249, .07); }
tr:last-child td { border-bottom: 0; }
@media (max-width: 1180px) {
  .sidebar { width: 300px; }
  .main-stage { margin-left: 300px; padding: 28px 28px 70px; }
  .hero { grid-template-columns: 1fr; }
  .hero-orbit { display: none; }
  .page-toc { display: none; }
}
@media (max-width: 860px) {
  .sidebar {
    position: static;
    width: auto;
    max-height: none;
    border-right: 0;
    border-bottom: 1px solid var(--border);
  }
  .main-stage { margin-left: 0; padding: 20px 14px 56px; }
  .hero { min-height: 0; padding: 28px 22px; border-radius: 24px; }
  .hero h1 { font-size: 38px; letter-spacing: -.05em; }
  .hero-stats { grid-template-columns: repeat(2, minmax(0, 1fr)); }
  .doc-article { padding: 24px 18px 40px; border-radius: 24px; }
}
""".strip()
    js = """
(function () {
  const sidebar = document.querySelector(".sidebar");
  const key = "unilab-rl-docs-sidebar-scroll";
  if (!sidebar || !window.sessionStorage) return;

  const saved = Number(window.sessionStorage.getItem(key));
  if (Number.isFinite(saved)) {
    requestAnimationFrame(() => {
      sidebar.scrollTop = saved;
    });
  }

  const saveScroll = () => {
    window.sessionStorage.setItem(key, String(sidebar.scrollTop));
  };

  sidebar.addEventListener("scroll", saveScroll, { passive: true });
  sidebar.addEventListener(
    "click",
    (event) => {
      const target = event.target instanceof Element ? event.target : null;
      if (target && target.closest("a[href]")) saveScroll();
    },
    true
  );
  window.addEventListener("pagehide", saveScroll);
})();

(async function () {
  const input = document.getElementById("search");
  const box = document.getElementById("search-results");
  if (!input || !box || !window.SEARCH_INDEX_URL) return;
  const response = await fetch(window.SEARCH_INDEX_URL);
  const pages = await response.json();
  const prefix = window.SITE_ROOT_PREFIX || "";
  input.addEventListener("input", () => {
    const q = input.value.trim().toLowerCase();
    box.innerHTML = "";
    if (!q) return;
    const hits = pages.filter((p) => (p.title + " " + p.category + " " + p.text).toLowerCase().includes(q)).slice(0, 8);
    if (!hits.length) {
      box.textContent = "没有匹配结果";
      return;
    }
    const list = document.createElement("ul");
    for (const hit of hits) {
      const item = document.createElement("li");
      const link = document.createElement("a");
      const title = document.createElement("strong");
      const meta = document.createElement("small");
      link.href = prefix + hit.href;
      title.textContent = hit.title;
      meta.textContent = hit.category;
      link.appendChild(title);
      link.appendChild(meta);
      item.appendChild(link);
      list.appendChild(item);
    }
    box.appendChild(list);
  });
})();

(function () {
  const toc = document.querySelector(".page-toc");
  if (!toc) return;
  const links = Array.from(toc.querySelectorAll("a[href^='#']"));
  const headings = links
    .map((link) => document.getElementById(decodeURIComponent(link.getAttribute("href").slice(1))))
    .filter(Boolean);
  if (!links.length || !headings.length) return;

  const setActive = () => {
    let active = headings[0];
    for (const heading of headings) {
      if (heading.getBoundingClientRect().top <= 140) {
        active = heading;
      } else {
        break;
      }
    }
    const id = active.id;
    for (const link of links) {
      const isActive = link.getAttribute("href") === "#" + id;
      link.classList.toggle("active", isActive);
      if (isActive) link.scrollIntoView({ block: "nearest" });
    }
  };

  setActive();
  window.addEventListener("scroll", setActive, { passive: true });
})();
""".strip()
    (SITE_ROOT / "site.css").write_text(css + "\n", encoding="utf-8")
    (SITE_ROOT / "site.js").write_text(js + "\n", encoding="utf-8")


def _plain_text(markdown: str) -> str:
    _, body = _strip_front_matter(markdown)
    body = re.sub(r"```.*?```", " ", body, flags=re.S)
    body = re.sub(r"!\[[^\]]*]\([^)]+\)", " ", body)
    body = re.sub(r"\[([^\]]+)]\([^)]+\)", r"\1", body)
    body = re.sub(r"[#|`>*_-]+", " ", body)
    return re.sub(r"\s+", " ", body).strip()


def build_site() -> None:
    if SITE_ROOT.exists():
        shutil.rmtree(SITE_ROOT)
    SITE_ROOT.mkdir(parents=True)
    pages = collect_pages()

    images_src = DOC_ROOT / "images"
    if images_src.exists():
        shutil.copytree(images_src, SITE_ROOT / "images")

    search_index = []
    for page in pages:
        markdown = page.source.read_text(encoding="utf-8")
        html_body = markdown_to_html(markdown)
        page.output.parent.mkdir(parents=True, exist_ok=True)
        page.output.write_text(_layout(page, pages, html_body), encoding="utf-8")
        search_index.append(
            {
                "title": page.title,
                "category": page.category,
                "href": str(page.rel_output),
                "text": _plain_text(markdown)[:6000],
            }
        )

    write_assets()
    (SITE_ROOT / "search-index.json").write_text(
        json.dumps(search_index, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"built static site: {SITE_ROOT.relative_to(REPO_ROOT)}/index.html pages={len(pages)}")


if __name__ == "__main__":
    build_site()
